// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALW59gx2aHGvIFvJQ4hkuCTTwCbAcS6IA',
    appId: '1:927111678072:web:f4d083c2855d5d3a2b058d',
    messagingSenderId: '927111678072',
    projectId: 'wholuh-72a15',
    authDomain: 'wholuh-72a15.firebaseapp.com',
    storageBucket: 'wholuh-72a15.firebasestorage.app',
    measurementId: 'G-JYF9M361XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsP_XZrQYnAn3xJmulc-mnmbGhBUOPQYE',
    appId: '1:927111678072:android:e7c7cc718c84d32e2b058d',
    messagingSenderId: '927111678072',
    projectId: 'wholuh-72a15',
    storageBucket: 'wholuh-72a15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkkh93fJ5_iolpF6_90HWYwvHDOTALyK0',
    appId: '1:927111678072:ios:a8587a2673ad29332b058d',
    messagingSenderId: '927111678072',
    projectId: 'wholuh-72a15',
    storageBucket: 'wholuh-72a15.firebasestorage.app',
    iosBundleId: 'com.example.wholuh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkkh93fJ5_iolpF6_90HWYwvHDOTALyK0',
    appId: '1:927111678072:ios:a8587a2673ad29332b058d',
    messagingSenderId: '927111678072',
    projectId: 'wholuh-72a15',
    storageBucket: 'wholuh-72a15.firebasestorage.app',
    iosBundleId: 'com.example.wholuh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALW59gx2aHGvIFvJQ4hkuCTTwCbAcS6IA',
    appId: '1:927111678072:web:854d9e45fcad71a52b058d',
    messagingSenderId: '927111678072',
    projectId: 'wholuh-72a15',
    authDomain: 'wholuh-72a15.firebaseapp.com',
    storageBucket: 'wholuh-72a15.firebasestorage.app',
    measurementId: 'G-LFGLS5NVSW',
  );
}
